//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public int Id { get; set; }
        public byte[] Screen1 { get; set; }
        public System.DateTime Time { get; set; }
        public double CursorX { get; set; }
        public double CursorY { get; set; }
    }
}
